---
title: "MyBrand"
editor: visual
---

#### [**Resources**]{.smallcaps}

[**Original Article**](https://www.stephaniehicks.com/blog/building-a-brand-as-a-scientist/)

#### [**Question-1**]{.smallcaps}

**Who are you? What makes you special?**

I am a passionate enthusiast for academic research. My diverse academic background and research skills make me exceptionally sensitive to interdisciplinary research.

#### [**Question-2**]{.smallcaps}

**What is your goal?**

Since entering the field of research, countless mentors and advisors have inspired me to move forward on the academic path. My short-term goal is to obtain a PhD degree within 5 years and publish my own perspectives in top-tier journals. As for long-term goals, academia is not my only choice; I also have my own experience and understanding in entrepreneurship and industry practice. In fact, beyond academia, engaging with, understanding, and grasping industry information is a great pleasure for me. I am willing to be part of the entrepreneurial world or work as an industry analyst. Overall, these things are interconnected.

#### [**Other Questions**]{.smallcaps}

-   Who are you? What makes you special?
-   What do you stand for? For example, maybe you are passionate about open science and you prioritize publishing in open-access journals or publishing open source software.
-   Who is your audience? This is important in terms of helping you understand your professional community as a scientist. What does the community value or not value? Does this align with your interests?
-   What is your goal? This is a very personal question and there are no wrong answers. However, it is helpful to understand what your short-term and long-terms goals are. Some questions you might think about as you try to answer these two questions are:
-   What motivates you?
-   What projects have others complimented you on?
-   Which projects can I spend hours on and not feel overwhelmed or drained?
-   Fill in the following: "I want to be a leader in ... \<\>" "In 5-10 years, I want to ... \<\< insert thing you want to have accomplished \>\>"
